version: "3"

services:
  db:
    image: mysql:5.7.24
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "gWJR2HynAy"
      MYSQL_DATABASE: "medical_scheduling"
      MYSQL_USER: "medical"
      MYSQL_PASSWORD: "abc123456*"
    volumes:
      - medical-scheduling-dbdata:/var/lib/mysql
    ports:
      - "3309:3306"
  app:
    build: .
    image: allisondev/docker-laravel
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    ports:
      - "8888:80"
    volumes:
      - ./../src:/var/www/
  redis:
    image: redis
    ports:
        - "63790:6379"
volumes:
  web-app:
    driver: local
  medical-scheduling-dbdata:
    driver: local